apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fraud-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fraud_platform
            - name: POSTGRES_USER
              value: fraud
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fraud-platform-secrets
                  key: POSTGRES_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 20
